baseURL = 'https://darius-sas.github.io/'
languageCode = 'en-us'
title = "darius-sas-website"
theme = "hugo-theme-console"
googleAnalytics = 'G-RZ06SEST8Z'

[params]
  # Cutting off the page title to two chars for mobile (console-demo -> co)
  titleCutting = true

  # Set the animation style -- https://animate.style/
  # To disable animations, please remove or comment animationStyle parameter
  animateStyle = "animated zoomIn fast" 

  [[params.navlinks]]
  name = "research/"
  url = "research/"
  
  [[params.navlinks]]
  name = "personal/"
  url = "personal/"

  [[params.navlinks]]
  name = "curriculum/"
  url = "curriculum/"

  [[params.navlinks]]
  name = "posts/"
  url = "posts/"

